# Configuration for Community Detection Pipeline

# Data settings
data_dir: data
sample_size: 100000  # Set to null for full graph

# Algorithm parameters
size_threshold: 1000  # Communities larger than this will be refined
target_subcommunities: 5  # Target number of subcommunities in refinement
modularity_threshold: 0.3  # Communities with modularity below this will be enhanced with Infomap
