# Configuration for Community Detection Pipeline

# Data settings
data_dir: data
sample_size: 10000  # Reduced from 100000 for better performance

# Algorithm parameters
size_threshold: 500  # Communities larger than this will be refined
target_subcommunities: 5  # Target number of subcommunities in refinement
modularity_threshold: 0.3  # Communities with modularity below this will be enhanced with Infomap
edge_file: edge_file.txt

# Performance optimization settings
max_iterations: 50  # Limit Girvan-Newman iterations
time_limit: 300  # 5 minute time limit per algorithm
fast_mode: true  # Use approximation algorithms for large graphs

# Output settings
output_dir: results  # Directory for saving results
visualization_dir: community_visualizations  # Directory for visualizations